services:
  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  backend:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - mongo
      - kafka

  datadog:
    image: datadog/agent:latest
    environment:
      - DD_API_KEY=
      - DD_SITE=us5.datadoghq.com
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8126:8126"

  dynatrace:
    image: dynatrace/oneagent:latest
    environment:
      - ONEAGENT_INSTALLER_SCRIPT_URL=https://gmt78264.live.dynatrace.com/api/v1/deployment/installer/agent/unix/default/latest?arch=x86
      - ONEAGENT_INSTALLER_DOWNLOAD_TOKEN=dt0c01.4IWHHUP7FHDKSW7N7LZJ36UW.7ZJ7U4U6HBVNUDIH3JIYY5KEVZOAPJPRIGWTKFQ47OJVPBHMDM7HSTF45PVMM4YS
    privileged: true
    pid: "host"
    network_mode: "host"
    volumes:
      - /:/mnt/root:ro

volumes:
  mongo_data: 
